### ISSUE TITLE
Procedure for upgrading/switching from original driver?

### ISSUE THREAD

**Issue by atyshka** [roadrunner2/macbook12-spi-driver#25]
Hi, thanks for working on this great addition to mac support! I was wondering what the procedure would be for switching from the original driver with no touch bar support over to your fork. Just clone and install following the same procedure? Do I need to make sure the old version is completely purged? Running kernel 4.15.

**Comment by roadrunner2** [comment]
Yes, you can just re-clone and build (or you can also just add a new remote and fetch/pull that, or even just change the remote to point to this repo and fetch/pull again). It should not be necessary to purge anything, as this repo just extends cb22's with the touchbar/als drivers, and generally all changes to the keyboard driver are submitted back to cb22 (though he hasn't been merging the pull requests of late, so consider this repo are a more up-to-date version).
