### ISSUE TITLE
mbp15 No keyboard/touchpad on 5.4.11

### ISSUE THREAD

**Issue by TRPB** [roadrunner2/macbook12-spi-driver#37]
I'm using aunali's kernel from here: https://packages.aunali1.com/archlinux/mbp/x86_64/ 

Since I upgraded, I've had no keyboard or touchpad.

I've installed the spi driver from the mbp15 branch which was working fine. I rebuilt it even though it shouldn't be necessary. 

Although it was working on 5.4.8 I can't downgrade* to test to see if it's something else. The BCE driver is working as I have wifi and audio so I'm assuming the issue is the spi driver. Is there any way I can debug this? What steps can I take to work out what's not working? 

There's nothing in dmesg to indicate an issue but if i run `lsmod | grep apple` this is all I get:

```
apple_gmux             20480  0
apple_bl               20480  1 apple_gmux
apple_bce              98304  1
snd_pcm               135168  5 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,apple_bce,snd_hda_core
snd                   106496  11 snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_timer,apple_bce,snd_pcm
```

`hid_apple` is missing, as is `apple_ibridge`. Modprobing those modules makes no difference so I'm guessing it's something else that's missing?

*Long story: as I don't have the packages (unfortunately aunali's server always times out through pacman so the don't get cached).The only other version I have available is 5.3.5 and I can't build the BCE driver if I boot that kernel because GCC says "incompatible gcc/plugin versions"

**Comment by roadrunner2** [comment]
The MBP15,*'s do not use this driver for keyboard and trackpad, but instead use the BCE and standard USB keyboard/trackpad drivers. The mbp15 branch here is only for the touchbar and ALS (there's no SPI driver in that branch).

Closing this issue, as the problem you outline is already being discussed and tracked at Dunedan/mbp-2016-linux#71.
