### ISSUE TITLE
Key release event getting lost if fn key changes touchbar mode

### ISSUE THREAD

**Issue by mzanetti** [roadrunner2/macbook12-spi-driver#5]
Steps to reproduce:
* Press and hold fn to switch between F keys and Media keys.
* press and hold key on the touchbar
* release fn
* release touchbar

=> you'll end up with repeated key pressed events and no key release event coming in any more.

(same happens the other way round btw, first press touchbar key, then press fn, release touchbar, release fn)

**Comment by roadrunner2** [comment]
@mzanetti Thanks for the report! Not sure how I managed to miss this, but it's fixed now.
