### ISSUE TITLE
repo info

### ISSUE THREAD

**Issue by jamarFraction** [roadrunner2/macbook12-spi-driver#6]
these lines:
`git clone https://github.com/cb22/macbook12-spi-driver.git /usr/src/applespi-0.1`
and 
`git clone https://github.com/cb22/macbook12-spi-driver.git /usr/src/applespi-0.1`
reference the forked repo and not yours, so when installing on a touchbar mac the appletb driver isn't included after running `dkms install -m applespi -v 0.1`

changing "cb22" to "roadrunner2" worked.

Many thanks for your hard work!

**Comment by roadrunner2** [comment]
Ah, you mean in the README? Good catch! Fixed now. Thanks.
